# coding: utf-8
CUDA = 0

GLOVE_SIZE = 300
HIDDEN_SIZE = 16
LAYER = 1
DROPOUT = 0.0
LEARNING_RATE = 5e-2
RANDOM_SWAP = 0.00

INF_N = 0
INF_LAMBDA = 0.4

OBJ_KG = False
OBJ_N_POST = -1
OBJ_ENH_POST = 0.1
OBJ_IGNORE_POST = -1
OBJ_N_RES = 2
OBJ_ENH_RES = 0.1
OBJ_IGNORE_RES = 0

BATCH_SIZE = 2
MAX_EPOCH = 100

BUCKET_SIZE = [[50, 50]]
MAX_DIALOG_CORPUS_SIZE = 30
MAX_VOCAB_SIZE = 10000
MAX_GROVE_TEST = -1

MAX_TEST_DIALOG_CORPUS_SIZE = 10
MAX_TEST_LENGTH = 40

MAX_VISUALIZE_DIALOG_CORPUS_SIZE = 1
MAX_VISUALIZE_WIDTH = 20
VISUALIZE_LOG = True
