# coding: utf-8
CUDA = 0

# Training
GLOVE_SIZE = 300
HIDDEN_SIZE = 16
LAYER = 1
DROPOUT = 0.0
LEARNING_RATE = 5e-2
RANDOM_SWAP = 0.00

OBJ_INF_N = 1
OBJ_INF_LAMBDA = 0.4

OBJ_KG_N = 2
OBJ_KG_ENH = 0.2
OBJ_KG_POST = True
OBJ_KG_RES = True
OBJ_KG_IDF = True

BATCH_SIZE = 2
MAX_EPOCH = 100

BUCKET_SIZE = [[50, 50]]
MAX_DIALOG_CORPUS_SIZE = 500000
MAX_VOCAB_SIZE = 30000
MAX_GROVE_TEST = 100

# Test
MAX_TEST_DIALOG_CORPUS_SIZE = 10
MAX_TEST_LENGTH = 40
IGNORE_UNK = True

TEST_INF_N = 0
TEST_KG_IDF = True

# Visualize
MAX_VISUALIZE_DIALOG_CORPUS_SIZE = 1
MAX_VISUALIZE_WIDTH = 20
VISUALIZE_LOG = True
